### ISSUE TITLE
Tigershark command not working.

### ISSUE THREAD

**Issue by batsgay** [s1l3nt78/TigerShark#4]
Hi, I am using hyper.js on a Windows 10 laptop. Everything seemed to install fine but at the end the opt/tigershark option failed. So I thought to myself that the tigershark command would still work but to my surprise it didn't. Whenever I type in tigershark it shows : bash: command not found tigershark: 
I've tried updating the software but it still didn't work. And if I press yes to opt/tigershark then it gives an error saying there is no tigershark directory.
I hope you can give some quick feedback and guide me through this issue. 

Here's a screenshot.
https://gyazo.com/2ab6c2c1f9fab639be0dda290a4dd74e

**Comment by s1l3nt78** [comment]
Yes windows has problems with allowing access to privileged folders.
either run everything as root. <sudo bash> before you start working with tigershark.
Otherwise goto where the TigerShark directory is eg. if its in /home/user/TigerShark
Goto /home/user and copy and paste the following command:
sudo mv TigerShark -t /opt && cd /opt/TigerShark && sudo cp tigershark -t /usr/sbin

NOTE: TigerShark works best from a proper Linux system as windows will flag your payloads and hinder creation

**Comment by batsgay** [comment]
I've copy pasted the same line of code into my terminal and to my surprise it worked but I'm now met with a new issue. When I type in tigershark to well start tigershark the following error appears:
/usr/sbin/tigershark: line 259: syntax error near unexpected token `newline'
/usr/sbin/tigershark: line 259: `               "CuteIt"'
I don't know how to solve this, could you please guide me?
Here's the screenshot : https://gyazo.com/cb8953189b558a2d4137af3c7edba3f6

**Comment by batsgay** [comment]
Hey, I know you've closed the issue but a new problem appeared. If you
would be kind enough to check GitHub and guide me through the issue.
Thanks in advance for your help.

**Comment by s1l3nt78** [comment]
# hi, this is an error i have made in the code. thanks for pointing it out. ill fix it in the next 30mins then just run sudo rm tigershark && git pull then rerun the cp tigershark part of the last command.

**Comment by batsgay** [comment]
Alright, thanks for the quick response. Hope your code fixing goes well.
Have a good day and I'll inform you if there are any more issues.

**Comment by batsgay** [comment]
Okay so I've done all that and the tigershark command finally works but now there are more errors than ever before.
Everytime I type in the command 'tigershark' it works alright but there is an error saying :
/usr/sbin/tigershark: line 457: figlet: command not found

Secondly, If I try doing anything for example start a  phishing campaign with SocialPhish the following errors will show up : 

./Modules/Phishing/Trawler/gophish.sh: line 11: figlet: command not found
python3: can't open file 'SocialFish.py': [Errno 2] No such file or directory
./Modules/Phishing/Trawler/socialfish.sh: line 19: ./tigershark: No such file or directory

Either no such file or directory will show up or permission denied will show up. This happens with all the options in every sector.
I don't know if there is a bug in your code or is tigershark not compatible with windows at all.

Below are some screenshots of the different errors : 
https://gyazo.com/63a6bad873f3677c32555fdcd7e4de4a
https://gyazo.com/ef0213f4b0d1d28798029c7b610cc650
https://gyazo.com/c22841d712e387969f57964a06f7cbec

NOTE: I've used the tigershark command with both sudo and nothing infront of it but the results are the same, either the error is permission denied, figlet: command not found or no such file or directory.

**Comment by s1l3nt78** [comment]
please stop using this on windows. as you will continuously have issues. the issue you are getting are because not all the commands and modules work on windows. These are also all very easy to fix problems. please learn more about linux and how to use bash before commenting that there are issues. This program is freeware and as such i am paid nothing to develop and fix problems that a beginning should understand how to fix. figlet is just a decorative text program which is gotten by sudo apt-get install figlet. nor does it have any impact on the program.

**Comment by s1l3nt78** [comment]
you will always get permission denied while using linux subsystem on windows.

**Comment by s1l3nt78** [comment]
please also make sure tigershark file in '/opt/TigerShark' is executable by running chmod +x on it

**Comment by batsgay** [comment]
I did run chmod +x /opt/TigerShark, but the no such file or directory and
the line 11: figlet command not found error still appears. So TigerShark is
still unusable sadly :/

**Comment by batsgay** [comment]
Also I get your comment saying this won't properly work on windows and I
should use a proper linux system. Thanks for clearing that this won't work
in windows. I'll try it out on an actual Linux distro instead. Thanks
for your help and have a nice day.

**Comment by batsgay** [comment]
And also I'm new to the bash and linux world so mind my noobish mistakes. I
wasn't trying to say your code is bad or anything, I just wanted some help
to figure this out. Cheers and have a nice day.

**Comment by s1l3nt78** [comment]
sorry man didnt mean to come off so harshly, just a long day. yeah unfortunately windows because of hows its made to avoid infection has too many problems when using this program as it basically just creates infections files used for a phishing campaign. you would need to run chmod +x /opt/TigerShark/tigershark for a file. for the directory chmod +x -R /opt/TigerShark to make the whole directory executable. but rather run "cd /opt/TigerShark && chmod +x -R tigershark Modules/" and sudo apt-get install figlet should fix figlet issue otherwise its not available from which ever repository your windows terminal is fetching from

**Comment by batsgay** [comment]
Nah its fine man we've all been there. Mhm i fixed the figlet issue by
typing out that command. And I also typed in the chmod thingy but the
issues still seems to persist. I still get permission denied and there is
no such file or directory errors. But as I said, ill stop trying this on
Windows and try again on a linux distro instead. Any distros you specially
recommend?

**Comment by s1l3nt78** [comment]
Kali or Parrot OS are in my opinion the best distros when it comes to penetration testing (hacking)
