### ISSUE TITLE
Bleh

### ISSUE THREAD

**Issue by AvOiDiNlAw** [s1l3nt78/TigerShark#8]
It Simply doesen't work everytime I try to do something It says permission denied or error in the code and It specifies the line of the code

**Comment by s1l3nt78** [comment]
1. Well a screenshot would be helpful to sort out the issue 🙂
2. It Simply `does` work, as plenty people use it with no issue.

But should you provide me with a screenshot i will be more then happy to help
Otherwise please remove with `sudo rm -rf /opt/TigerShark` and reclone & re-install. (This generally fixes most issues due to a possibly inturrupted install script for a multitude of reasons)
